from io import TextIOWrapper
from typing import overload

@overload
def creature() -> str: ...
@overload
def creature(path: str) -> None: ...
@overload
def creature(file: TextIOWrapper) -> None: ...

@overload
def game() -> str: ...
@overload
def game(path: str) -> None: ...
@overload
def game(file: TextIOWrapper) -> None: ...
